esphome:
  min_version: '2025.2.0'

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

logger:
  hardware_uart: USB_SERIAL_JTAG

psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: bus_a
    sda: GPIO8
    scl: GPIO18

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO45
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO2

audio_adc:
  - platform: es7210
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

audio_dac:
  - platform: es8311
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 48000

microphone:
  - platform: i2s_audio
    id: box_mic
    sample_rate: 16000
    i2s_din_pin: GPIO16
    bits_per_sample: 16bit
    adc_type: external

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_dout_pin: GPIO15
    dac_type: external
    sample_rate: 48000
    bits_per_sample: 16bit
    channel: left
    audio_dac: es8311_dac
    buffer_duration: 100ms

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    id: mic_muted
    name: Microphone Muted
    icon: "mdi:microphone-off"

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true
    id: boot_button
    name: Boot Button
    entity_category: diagnostic

  - platform: gt911
    id: touch_button
    name: Touch Button
    index: 0

output:
  - platform: ledc
    pin: GPIO47
    id: backlight_output

light:
  - platform: monochromatic
    id: backlight
    name: Screen Backlight
    icon: "mdi:television"
    entity_category: config
    output: backlight_output
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

spi:
  - id: spi_bus
    clk_pin: GPIO7
    mosi_pin: GPIO6

display:
  - platform: ili9xxx
    id: screen
    model: S3BOX
    invert_colors: false
    data_rate: 40MHz
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    update_interval: never

touchscreen:
  - platform: gt911
    id: touch
    display: screen
    i2c_id: bus_a
    interrupt_pin:
      number: GPIO3
      ignore_strapping_warning: true
    calibration:
      x_min: 0
      y_min: 0
      x_max: 240
      y_max: 320
    on_update:
      - lambda: |-
          for (auto touch: touches)  {
              if (touch.state <= 2) {
                ESP_LOGI("screen", "Touch points: id=%d x=%d y=%d", touch.id, touch.x, touch.y);
              }
          }
