# Based on https://github.com/esphome/media-players/blob/main/raspiaudio/raspiaudio-muse-luxe.yaml

esphome:
  min_version: 2025.7.0
  name_add_mac_suffix: true

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

i2c:
  - id: i2c_bus
    sda: GPIO18
    scl: GPIO23

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5

# audio_dac:
#   - platform: es8388

# media_player:
#   - platform: i2s_audio
#     name: None
#     id: luxe_out
#     dac_type: external
#     i2s_dout_pin: GPIO26
#     mode: stereo
#     mute_pin:
#       number: GPIO21
#       inverted: true

# microphone:
#   - platform: i2s_audio
#     id: luxe_microphone
#     i2s_din_pin: GPIO35
#     adc_type: external
#     pdm: false

# sensor:
#   - platform: adc
#     id: battery_sensor
#     pin: GPIO33
#     name: Battery
#     icon: "mdi:battery-outline"
#     device_class: voltage
#     state_class: measurement
#     entity_category: diagnostic
#     unit_of_measurement: V
#     update_interval: 15s
#     accuracy_decimals: 3
#     attenuation: 11db
#     raw: true
#     filters:
#       - multiply: 0.00173913  # 2300 -> 4, for attenuation 11db, based on Olivier's code
#       - exponential_moving_average:
#           alpha: 0.2
#           send_every: 2
#       - delta: 0.002

# binary_sensor:
#   - platform: gpio
#     id: volume_up
#     name: Volume Up
#     pin:
#       number: GPIO19
#       inverted: true
#       mode:
#         input: true
#         pullup: true
#     on_click:
#       - media_player.volume_up:
#           id: luxe_out
#   - platform: gpio
#     id: volume_down
#     name: Volume Down
#     pin:
#       number: GPIO32
#       inverted: true
#       mode:
#         input: true
#         pullup: true
#     on_click:
#       - media_player.volume_down:
#           id: luxe_out
#   - platform: gpio
#     id: action_button
#     name: Action Button
#     pin:
#       number: GPIO12
#       inverted: true
#       mode:
#         input: true
#         pullup: true

light:
  - platform: fastled_clockless
    id: activity_led
    pin: GPIO22
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    gamma_correct: 2.8
