# Based on https://github.com/esphome/media-players/blob/main/raspiaudio/raspiaudio-muse-luxe.yaml

esphome:
  min_version: 2025.7.0
  name_add_mac_suffix: true

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

sensor:
  - platform: adc
    id: battery_sensor
    pin: GPIO33
    name: Battery
    icon: "mdi:battery-outline"
    device_class: voltage
    state_class: measurement
    entity_category: diagnostic
    unit_of_measurement: V
    update_interval: 15s
    accuracy_decimals: 3
    attenuation: 11db
    raw: true
    filters:
      - multiply: 0.00173913  # 2300 -> 4, for attenuation 11db, based on Olivier's code
      - exponential_moving_average:
          alpha: 0.2
          send_every: 2
      - delta: 0.002

binary_sensor:
  - platform: gpio
    id: volume_up
    name: Volume Up
    pin:
      number: GPIO19
      inverted: true
      mode:
        input: true
        pullup: true
    # on_click:
    #   - media_player.volume_up:
    #       id: luxe_out
  - platform: gpio
    id: volume_down
    name: Volume Down
    pin:
      number: GPIO32
      inverted: true
      mode:
        input: true
        pullup: true
    # on_click:
    #   - media_player.volume_down:
    #       id: luxe_out
  - platform: gpio
    id: action_button
    name: Action Button
    pin:
      number: GPIO12
      ignore_strapping_warning: true
      inverted: true
      mode:
        input: true
        pullup: true

light:
  - platform: esp32_rmt_led_strip
    id: activity_led
    pin: GPIO22
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    gamma_correct: 2.8
