switch:
  - platform: gpio
    id: dac_mute
    name: DAC Mute
    entity_category: diagnostic
    restore_mode: ALWAYS_ON
    pin:
      number: GPIO21
      inverted: true

i2c:
  - id: i2c_bus
    sda: GPIO18
    scl: GPIO23

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin:
      number: GPIO5
      ignore_strapping_warning: true

audio_dac:
  - platform: es8388

speaker:
  - platform: i2s_audio
    id: i2s_speaker
    dac_type: external
    i2s_dout_pin: GPIO26
    channel: stereo
  - platform: mixer
    output_speaker: i2s_speaker
    source_speakers:
      - id: announcement_speaker
      - id: media_speaker

media_player:
  - platform: speaker
    id: luxe_out
    name: None
    announcement_pipeline:
      speaker: announcement_speaker
    media_pipeline:
      speaker: media_speaker

# microphone:
#   - platform: i2s_audio
#     id: luxe_microphone
#     i2s_din_pin: GPIO35
#     adc_type: external
#     pdm: false

binary_sensor:
  - id: !extend volume_up
    on_click:
      then:
        - media_player.volume_up: luxe_out
  - id: !extend volume_down
    on_click:
      then:
        - media_player.volume_down: luxe_out
