# Based on https://github.com/RASPIAUDIO/esphomeLuxe/blob/main/luxe_microWW.yaml

switch:
  - platform: gpio
    id: dac_mute
    name: DAC Mute
    entity_category: diagnostic
    restore_mode: ALWAYS_ON
    pin:
      number: GPIO21
      inverted: true

i2c:
  - id: i2c_bus
    sda: GPIO18
    scl: GPIO23

i2s_audio:
  - id: i2s0
    i2s_lrclk_pin: GPIO25
    i2s_mclk_pin:
      number: GPIO0
      ignore_strapping_warning: true
    i2s_bclk_pin:
      number: GPIO5
      ignore_strapping_warning: true

audio_dac:
  - platform: es8388

select:
  - platform: es8388
    dac_output:
      name: "DAC Output"
    # adc_input_mic:
    #   name: "ADC Input MIC"

speaker:
  - platform: i2s_audio
    id: luxe_speaker
    i2s_audio_id: i2s0
    i2s_dout_pin: GPIO26
    dac_type: external
    sample_rate: 48000
    bits_per_sample: 16bit
    num_channels: 2
    buffer_duration: 100ms
  - platform: mixer
    output_speaker: luxe_speaker
    source_speakers:
      - id: announcement_speaker
      - id: media_speaker

media_player:
  - platform: speaker
    id: luxe_out
    name: None
    announcement_pipeline:
      speaker: announcement_speaker
      format: WAV
      sample_rate: 48000
      num_channels: 1
    media_pipeline:
      speaker: media_speaker
      format: WAV
      sample_rate: 48000
      num_channels: 1

# microphone:
#   - platform: i2s_audio
#     id: luxe_microphone
#     i2s_din_pin: GPIO35
#     adc_type: external
#     pdm: false

binary_sensor:
  - id: !extend volume_up
    on_click:
      then:
        - media_player.volume_up: luxe_out
  - id: !extend volume_down
    on_click:
      then:
        - media_player.volume_down: luxe_out
