i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO16
    i2s_bclk_pin: GPIO5
    i2s_mclk_pin:
      number: GPIO0
      ignore_strapping_warning: true

audio_dac:
  - platform: es8388

output:
  - platform: gpio
    id: dac_mute
    pin:
      number: GPIO46
      inverted: true
      ignore_strapping_warning: true
      mode:
        output: true

microphone:
  - platform: i2s_audio
    id: mic
    i2s_din_pin: GPIO4
    adc_type: external
    pdm: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
      mode:
        input: true
        pullup: true
    id: jack_plugged
    name: Jack plugged in
    filters:
      - delayed_on_off: 0.3s
