substitutions:
  home_assistant_entity_id: ""
  feature_switch_id: auto_brightness
  brightness_multiplier: "1.0"
  min_brightness: "10"
  offset: "0"

sensor:
  - id: auto_brightness_target
    platform: homeassistant
    entity_id: $home_assistant_entity_id
    filters:
      - offset: $offset
      - multiply: $brightness_multiplier
      - clamp:
          min_value: $min_brightness
          max_value: 100
          ignore_out_of_range: false
    on_value:
      then:
        - script.execute: auto_brightness_update

script:
  - id: auto_brightness_update
    then:
      - if:
          condition:
            - switch.is_on: $feature_switch_id
          then:
            - logger.log:
                format: Updating brightness to %.0f percent
                args:
                  - id(auto_brightness_target).state
                tag: auto_brightness.update
                level: info
            - script.execute: auto_brightness_update_component
