esphome:
  min_version: 2024.9.1

esp8266:
  board: esp8285

logger:
  baud_rate: 0

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 19200

rf_bridge:

output:
  - id: output_led
    platform: gpio
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: binary
    id: wifi_led
    name: WiFi LED
    output: output_led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    id: reset_button
    name: Reset Button
