esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

light:
  - platform: esp32_rmt_led_strip
    id: ledstrip
    name: LED Strip
    rgb_order: GRB
    pin: GPIO8
    rmt_channel: 0
    num_leds: 24
    chipset: SK6812
    restore_mode: RESTORE_AND_OFF

matrix_keypad:
  id: keypad
  keys: ABCDEFGHIJKLMNOPQRSTUVWX
  rows:
    - pin: GPIO21
    - pin: GPIO20
    - pin: GPIO3
    - pin: GPIO7
  columns:
    - pin: GPIO0
    - pin: GPIO1
    - pin: GPIO10
    - pin: GPIO4
    - pin: GPIO5
    - pin: GPIO6

binary_sensor:
  - platform: matrix_keypad
    id: button_row_1_column_1
    name: Button Row 1 Column 1
    keypad_id: keypad
    key: A
  - platform: matrix_keypad
    id: button_row_1_column_2
    name: Button Row 1 Column 2
    keypad_id: keypad
    key: B
  - platform: matrix_keypad
    id: button_row_1_column_3
    name: Button Row 1 Column 3
    keypad_id: keypad
    key: C
  - platform: matrix_keypad
    id: button_row_1_column_4
    name: Button Row 1 Column 4
    keypad_id: keypad
    key: D
  - platform: matrix_keypad
    id: button_row_1_column_5
    name: Button Row 1 Column 5
    keypad_id: keypad
    key: E
  - platform: matrix_keypad
    id: button_row_1_column_6
    name: Button Row 1 Column 6
    keypad_id: keypad
    key: F
  - platform: matrix_keypad
    id: button_row_2_column_1
    name: Button Row 2 Column 1
    keypad_id: keypad
    key: G
  - platform: matrix_keypad
    id: button_row_2_column_2
    name: Button Row 2 Column 2
    keypad_id: keypad
    key: H
  - platform: matrix_keypad
    id: button_row_2_column_3
    name: Button Row 2 Column 3
    keypad_id: keypad
    key: I
  - platform: matrix_keypad
    id: button_row_2_column_4
    name: Button Row 2 Column 4
    keypad_id: keypad
    key: J
  - platform: matrix_keypad
    id: button_row_2_column_5
    name: Button Row 2 Column 5
    keypad_id: keypad
    key: K
  - platform: matrix_keypad
    id: button_row_2_column_6
    name: Button Row 2 Column 6
    keypad_id: keypad
    key: L
  - platform: matrix_keypad
    id: button_row_3_column_1
    name: Button Row 3 Column 1
    keypad_id: keypad
    key: M
  - platform: matrix_keypad
    id: button_row_3_column_2
    name: Button Row 3 Column 2
    keypad_id: keypad
    key: 'N'
  - platform: matrix_keypad
    id: button_row_3_column_3
    name: Button Row 3 Column 3
    keypad_id: keypad
    key: O
  - platform: matrix_keypad
    id: button_row_3_column_4
    name: Button Row 3 Column 4
    keypad_id: keypad
    key: P
  - platform: matrix_keypad
    id: button_row_3_column_5
    name: Button Row 3 Column 5
    keypad_id: keypad
    key: Q
  - platform: matrix_keypad
    id: button_row_3_column_6
    name: Button Row 3 Column 6
    keypad_id: keypad
    key: R
  - platform: matrix_keypad
    id: button_row_4_column_1
    name: Button Row 4 Column 1
    keypad_id: keypad
    key: S
  - platform: matrix_keypad
    id: button_row_4_column_2
    name: Button Row 4 Column 2
    keypad_id: keypad
    key: T
  - platform: matrix_keypad
    id: button_row_4_column_3
    name: Button Row 4 Column 3
    keypad_id: keypad
    key: U
  - platform: matrix_keypad
    id: button_row_4_column_4
    name: Button Row 4 Column 4
    keypad_id: keypad
    key: V
  - platform: matrix_keypad
    id: button_row_4_column_5
    name: Button Row 4 Column 5
    keypad_id: keypad
    key: W
  - platform: matrix_keypad
    id: button_row_4_column_6
    name: Button Row 4 Column 6
    keypad_id: keypad
    key: X



