esphome:
  min_version: '2025.7'
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

light:
  - platform: esp32_rmt_led_strip
    id: ledstrip
    name: LED Strip
    rgb_order: GRB
    pin:
      number: GPIO8
      ignore_strapping_warning: true
    num_leds: 24
    chipset: SK6812
    restore_mode: RESTORE_AND_OFF

matrix_keypad:
  id: keypad
  keys: ABCDEFGHIJKLMNOPQRSTUVWX
  rows:
    - pin: GPIO21
    - pin: GPIO20
    - pin: GPIO3
    - pin: GPIO7
  columns:
    - pin: GPIO0
    - pin: GPIO1
    - pin: GPIO10
    - pin: GPIO4
    - pin: GPIO5
    - pin: GPIO6
